"""Add Review model

Revision ID: 375fff67a467
Revises: b8581207ac77
Create Date: 2025-06-11 19:49:15.490059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375fff67a467'
down_revision = 'b8581207ac77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('space_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('review_text',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.alter_column('upi_qr_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.alter_column('upi_qr_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('review_text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('space_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
